- name: configure DB server
  become: yes
  hosts: db
  vars:
    login_hostname: db.muvva.online
  tasks:
  - name: installing mysql server
    ansible.builtin.dnf:
        name: mysql-server
        state: latest

  - name: starting and enabling mysql-server
    ansible.builtin.service:   
        name: mysqld
        state: started
        enabled: yes

  - name: checking whether able to connect db #if it connects,db password is already setup
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_hostname }}"
      filter: version
    ignore_errors: yes  #ignore errors if password is not setup
    register: mysql_connection_output # takes the output of previous command execution and register into the given variable

  - name: printing the connection output
    ansible.builtin.debug:
      msg: "The output of connecting to db host is:{{ mysql_connection_output }}"