- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and enable nginx
    ansible.builtin.service:
      state:  started
      enabled:  yes

  