- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state:  started
      enabled:  yes

  - name: delete default directory of html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state:  absent

  - name: creating the directory html
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state:  directory     #state shoukd be directory for creating the same